<?php
// @todo(mh) Add this back to the navigation renderer
// add warning to links that open in new tabs to improve accessibility, as recommended by WCAG20 G201
// $newTabInfo = sprintf('<span class="info-box display-on-hover"> %s </span>', $this->translate('opens in new window'));
if (empty($this->actions)) {
    return;
}
?>
<tr>
  <th><?= $this->translate('Actions') ?></th>
  <td><?= $this->actions->render(); ?></td>
</tr>
